# Generated by Django 5.2.7 on 2026-01-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
